CREATE DATABASE `ecommerce_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- ecommerce_db.planting_records definition

CREATE TABLE `planting_records` (
  `id` int NOT NULL AUTO_INCREMENT,
  `staff_name` varchar(100) NOT NULL,
  `quantity` int DEFAULT NULL,
  `order_date` date DEFAULT NULL,
  `wechat_id` varchar(100) DEFAULT NULL,
  `product_id` varchar(100) DEFAULT NULL,
  `keyword` varchar(200) DEFAULT NULL,
  `wangwang_id` varchar(100) DEFAULT NULL,
  `order_wechat` varchar(100) DEFAULT NULL,
  `order_number` varchar(100) DEFAULT NULL,
  `amount` float DEFAULT NULL,
  `gift_commission` float DEFAULT NULL,
  `refund_status` varchar(50) DEFAULT NULL,
  `refund_amount` float DEFAULT NULL,
  `refund_wechat` varchar(100) DEFAULT NULL,
  `refund_date` date DEFAULT NULL,
  `store_name` varchar(200) DEFAULT NULL,
  `internal_order_number` varchar(100) DEFAULT NULL,
  `remarks` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `uploaded_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `uploaded_by` (`uploaded_by`),
  KEY `idx_planting_records_matching` (`order_date`,`product_id`),
  CONSTRAINT `planting_records_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19729 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ecommerce_db.product_data definition

CREATE TABLE `product_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `platform` varchar(50) NOT NULL,
  `product_name` text,
  `tmall_product_code` varchar(100) DEFAULT NULL,
  `tmall_supplier_name` varchar(200) DEFAULT NULL,
  `visitor_count` int DEFAULT NULL,
  `page_views` int DEFAULT NULL,
  `search_guided_visitors` int DEFAULT NULL,
  `add_to_cart_count` int DEFAULT NULL,
  `favorite_count` int DEFAULT NULL,
  `payment_amount` float DEFAULT NULL,
  `payment_product_count` int DEFAULT NULL,
  `payment_buyer_count` int DEFAULT NULL,
  `search_guided_payment_buyers` int DEFAULT NULL,
  `unit_price` float DEFAULT NULL,
  `visitor_average_value` float DEFAULT NULL,
  `payment_conversion_rate` float DEFAULT NULL,
  `order_conversion_rate` float DEFAULT NULL,
  `avg_stay_time` float DEFAULT NULL,
  `detail_page_bounce_rate` float DEFAULT NULL,
  `order_payment_conversion_rate` float DEFAULT NULL,
  `search_payment_conversion_rate` float DEFAULT NULL,
  `refund_amount` float DEFAULT NULL,
  `refund_ratio` float DEFAULT NULL,
  `filename` varchar(255) NOT NULL,
  `upload_date` date NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `uploaded_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `uploaded_by` (`uploaded_by`),
  CONSTRAINT `product_data_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2409 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ecommerce_db.product_data_merge definition

CREATE TABLE `product_data_merge` (
  `id` int NOT NULL AUTO_INCREMENT,
  `product_data_id` int DEFAULT NULL,
  `platform` varchar(50) NOT NULL,
  `product_name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '产品',
  `tmall_product_code` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '天猫ID',
  `tmall_supplier_name` varchar(200) DEFAULT NULL,
  `visitor_count` int DEFAULT NULL COMMENT '访客数',
  `page_views` int DEFAULT NULL,
  `search_guided_visitors` int DEFAULT NULL COMMENT '自然搜索',
  `add_to_cart_count` int DEFAULT NULL COMMENT '加购',
  `favorite_count` int DEFAULT NULL COMMENT '收藏',
  `payment_amount` decimal(10,2) DEFAULT NULL COMMENT '前台成交金额',
  `payment_product_count` int DEFAULT NULL COMMENT '支付件数',
  `payment_buyer_count` int DEFAULT NULL COMMENT '前台订单笔数',
  `search_guided_payment_buyers` int DEFAULT NULL,
  `unit_price` decimal(10,2) DEFAULT NULL,
  `visitor_average_value` decimal(10,2) DEFAULT NULL,
  `payment_conversion_rate` decimal(5,4) DEFAULT NULL,
  `order_conversion_rate` decimal(5,4) DEFAULT NULL,
  `avg_stay_time` decimal(10,2) DEFAULT NULL,
  `detail_page_bounce_rate` decimal(5,4) DEFAULT NULL,
  `order_payment_conversion_rate` decimal(5,4) DEFAULT NULL,
  `search_payment_conversion_rate` decimal(5,4) DEFAULT NULL,
  `refund_amount` decimal(10,2) DEFAULT NULL COMMENT '退款金额',
  `refund_ratio` decimal(5,4) DEFAULT NULL,
  `filename` varchar(255) NOT NULL,
  `upload_date` date NOT NULL COMMENT '日期',
  `uploaded_by` int DEFAULT NULL,
  `product_list_id` int DEFAULT NULL,
  `product_list_name` varchar(500) DEFAULT NULL,
  `listing_time` date DEFAULT NULL COMMENT '上架时间',
  `product_list_created_at` datetime DEFAULT NULL,
  `product_list_updated_at` datetime DEFAULT NULL,
  `product_list_uploaded_by` int DEFAULT NULL,
  `is_matched` tinyint(1) DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `planting_orders` decimal(15,2) DEFAULT NULL COMMENT '种菜笔数',
  `planting_amount` decimal(15,2) DEFAULT NULL COMMENT '种菜金额',
  `planting_cost` decimal(15,2) DEFAULT NULL COMMENT '种菜成本',
  `planting_deduction` decimal(15,2) DEFAULT NULL COMMENT '种菜扣点',
  `planting_logistics_cost` decimal(15,2) DEFAULT NULL COMMENT '种菜物流成本',
  `keyword_promotion` decimal(15,2) DEFAULT NULL COMMENT '关键词推广',
  `sitewide_promotion` decimal(15,2) DEFAULT NULL COMMENT '全站推广',
  `product_operation` decimal(15,2) DEFAULT NULL COMMENT '货品运营',
  `crowd_promotion` decimal(15,2) DEFAULT NULL COMMENT '人群推广',
  `super_short_video` decimal(15,2) DEFAULT NULL COMMENT '超级短视频',
  `multi_target_direct` decimal(15,2) DEFAULT NULL COMMENT '多目标直投',
  `promotion_summary_updated_at` datetime DEFAULT NULL COMMENT '推广费用汇总更新时间',
  `planting_summary_updated_at` datetime DEFAULT NULL COMMENT '种菜汇总更新时间',
  `conversion_rate` decimal(10,2) DEFAULT NULL COMMENT '支付转化率',
  `favorite_rate` decimal(10,2) DEFAULT NULL COMMENT '收藏率',
  `cart_rate` decimal(10,2) DEFAULT NULL COMMENT '加购率',
  `uv_value` decimal(10,2) DEFAULT NULL COMMENT 'UV价值',
  `real_conversion_rate` decimal(10,2) DEFAULT NULL COMMENT '真实转化率',
  `real_amount` decimal(10,2) DEFAULT NULL COMMENT '真实金额',
  `real_buyer_count` int DEFAULT NULL COMMENT '真实买家数',
  `real_product_count` int DEFAULT NULL COMMENT '真实件数',
  `product_cost` decimal(10,2) DEFAULT NULL COMMENT '产品成本',
  `real_order_deduction` decimal(10,2) DEFAULT NULL COMMENT '真实订单扣点',
  `tax_invoice` decimal(10,2) DEFAULT NULL COMMENT '税票',
  `real_order_logistics_cost` decimal(10,2) DEFAULT NULL COMMENT '真实订单物流成本',
  `gross_profit` decimal(10,2) DEFAULT NULL COMMENT '毛利',
  PRIMARY KEY (`id`),
  KEY `idx_tmall_product_code` (`tmall_product_code`),
  KEY `idx_upload_date` (`upload_date`),
  KEY `idx_platform` (`platform`),
  KEY `idx_is_matched` (`is_matched`),
  KEY `idx_product_data_id` (`product_data_id`),
  KEY `idx_product_list_id` (`product_list_id`),
  KEY `idx_promotion_summary_updated` (`promotion_summary_updated_at`),
  KEY `idx_product_data_merge_planting_summary` (`upload_date`,`tmall_product_code`)
) ENGINE=InnoDB AUTO_INCREMENT=175 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ecommerce_db.product_list definition

CREATE TABLE `product_list` (
  `id` int NOT NULL AUTO_INCREMENT,
  `product_id` varchar(100) NOT NULL,
  `product_name` varchar(500) NOT NULL,
  `listing_time` date DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `uploaded_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `uploaded_by` (`uploaded_by`),
  CONSTRAINT `product_list_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `user` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1023 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ecommerce_db.subject_report definition

CREATE TABLE `subject_report` (
  `id` int NOT NULL AUTO_INCREMENT,
  `platform` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '天猫苏宁' COMMENT '平台',
  `report_date` date NOT NULL COMMENT '报表日期',
  `date_field` date DEFAULT NULL COMMENT '日期',
  `scene_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '场景ID',
  `scene_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '场景名字',
  `original_scene_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原二级场景ID',
  `original_scene_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原二级场景名字',
  `plan_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '计划ID',
  `plan_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '计划名字',
  `subject_id` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主体ID',
  `subject_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主体类型',
  `subject_name` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主体名称',
  `impressions` bigint DEFAULT NULL COMMENT '展现量',
  `clicks` bigint DEFAULT NULL COMMENT '点击量',
  `cost` decimal(15,2) DEFAULT NULL COMMENT '花费',
  `ctr` decimal(8,4) DEFAULT NULL COMMENT '点击率',
  `avg_cpc` decimal(10,2) DEFAULT NULL COMMENT '平均点击花费',
  `cpm` decimal(10,2) DEFAULT NULL COMMENT '千次展现花费',
  `total_presale_amount` decimal(15,2) DEFAULT NULL COMMENT '总预售成交金额',
  `total_presale_orders` int DEFAULT NULL COMMENT '总预售成交笔数',
  `direct_presale_amount` decimal(15,2) DEFAULT NULL COMMENT '直接预售成交金额',
  `direct_presale_orders` int DEFAULT NULL COMMENT '直接预售成交笔数',
  `indirect_presale_amount` decimal(15,2) DEFAULT NULL COMMENT '间接预售成交金额',
  `indirect_presale_orders` int DEFAULT NULL COMMENT '间接预售成交笔数',
  `direct_transaction_amount` decimal(15,2) DEFAULT NULL COMMENT '直接成交金额',
  `indirect_transaction_amount` decimal(15,2) DEFAULT NULL COMMENT '间接成交金额',
  `total_transaction_amount` decimal(15,2) DEFAULT NULL COMMENT '总成交金额',
  `total_transaction_orders` int DEFAULT NULL COMMENT '总成交笔数',
  `direct_transaction_orders` int DEFAULT NULL COMMENT '直接成交笔数',
  `indirect_transaction_orders` int DEFAULT NULL COMMENT '间接成交笔数',
  `click_conversion_rate` decimal(8,4) DEFAULT NULL COMMENT '点击转化率',
  `roas` decimal(8,4) DEFAULT NULL COMMENT '投入产出比',
  `total_transaction_cost` decimal(15,2) DEFAULT NULL COMMENT '总成交成本',
  `total_cart_count` int DEFAULT NULL COMMENT '总购物车数',
  `direct_cart_count` int DEFAULT NULL COMMENT '直接购物车数',
  `indirect_cart_count` int DEFAULT NULL COMMENT '间接购物车数',
  `cart_rate` decimal(8,4) DEFAULT NULL COMMENT '加购率',
  `favorite_product_count` int DEFAULT NULL COMMENT '收藏宝贝数',
  `favorite_shop_count` int DEFAULT NULL COMMENT '收藏店铺数',
  `shop_favorite_cost` decimal(15,2) DEFAULT NULL COMMENT '店铺收藏成本',
  `total_favorite_cart_count` int DEFAULT NULL COMMENT '总收藏加购数',
  `total_favorite_cart_cost` decimal(15,2) DEFAULT NULL COMMENT '总收藏加购成本',
  `product_favorite_cart_count` int DEFAULT NULL COMMENT '宝贝收藏加购数',
  `product_favorite_cart_cost` decimal(15,2) DEFAULT NULL COMMENT '宝贝收藏加购成本',
  `total_favorite_count` int DEFAULT NULL COMMENT '总收藏数',
  `product_favorite_cost` decimal(15,2) DEFAULT NULL COMMENT '宝贝收藏成本',
  `product_favorite_rate` decimal(8,4) DEFAULT NULL COMMENT '宝贝收藏率',
  `cart_cost` decimal(15,2) DEFAULT NULL COMMENT '加购成本',
  `placed_order_count` int DEFAULT NULL COMMENT '拍下订单笔数',
  `placed_order_amount` decimal(15,2) DEFAULT NULL COMMENT '拍下订单金额',
  `direct_favorite_product_count` int DEFAULT NULL COMMENT '直接收藏宝贝数',
  `indirect_favorite_product_count` int DEFAULT NULL COMMENT '间接收藏宝贝数',
  `coupon_claim_count` int DEFAULT NULL COMMENT '优惠券领取量',
  `shopping_gold_recharge_count` int DEFAULT NULL COMMENT '购物金充值笔数',
  `shopping_gold_recharge_amount` decimal(15,2) DEFAULT NULL COMMENT '购物金充值金额',
  `wangwang_consultation_count` int DEFAULT NULL COMMENT '旺旺咨询量',
  `guided_visit_count` int DEFAULT NULL COMMENT '引导访问量',
  `guided_visitor_count` int DEFAULT NULL COMMENT '引导访问人数',
  `guided_potential_customer_count` int DEFAULT NULL COMMENT '引导访问潜客数',
  `guided_potential_customer_rate` decimal(8,4) DEFAULT NULL COMMENT '引导访问潜客占比',
  `membership_rate` decimal(8,4) DEFAULT NULL COMMENT '入会率',
  `membership_count` int DEFAULT NULL COMMENT '入会量',
  `guided_visit_rate` decimal(8,4) DEFAULT NULL COMMENT '引导访问率',
  `deep_visit_count` int DEFAULT NULL COMMENT '深度访问量',
  `avg_visit_pages` decimal(8,2) DEFAULT NULL COMMENT '平均访问页面数',
  `new_customer_count` int DEFAULT NULL COMMENT '成交新客数',
  `new_customer_rate` decimal(8,4) DEFAULT NULL COMMENT '成交新客占比',
  `member_first_purchase_count` int DEFAULT NULL COMMENT '会员首购人数',
  `member_transaction_amount` decimal(15,2) DEFAULT NULL COMMENT '会员成交金额',
  `member_transaction_orders` int DEFAULT NULL COMMENT '会员成交笔数',
  `transaction_customer_count` int DEFAULT NULL COMMENT '成交人数',
  `avg_orders_per_customer` decimal(8,2) DEFAULT NULL COMMENT '人均成交笔数',
  `avg_amount_per_customer` decimal(15,2) DEFAULT NULL COMMENT '人均成交金额',
  `natural_traffic_amount` decimal(15,2) DEFAULT NULL COMMENT '自然流量转化金额',
  `natural_traffic_impressions` bigint DEFAULT NULL COMMENT '自然流量曝光量',
  `platform_boost_total_transaction` decimal(15,2) DEFAULT NULL COMMENT '平台助推总成交',
  `platform_boost_direct_transaction` decimal(15,2) DEFAULT NULL COMMENT '平台助推直接成交',
  `platform_boost_clicks` int DEFAULT NULL COMMENT '平台助推点击',
  `product_coupon_discount_amount` decimal(15,2) DEFAULT NULL COMMENT '宝贝优惠券抵扣金额',
  `product_coupon_total_transaction` decimal(15,2) DEFAULT NULL COMMENT '宝贝优惠券撬动总成交',
  `product_coupon_direct_transaction` decimal(15,2) DEFAULT NULL COMMENT '宝贝优惠券撬动直接成交',
  `product_coupon_clicks` int DEFAULT NULL COMMENT '宝贝优惠券撬动点击',
  `filename` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '上传的文件名',
  `upload_date` date NOT NULL COMMENT '用户选择的上传日期',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `uploaded_by` int DEFAULT NULL COMMENT '上传用户ID',
  PRIMARY KEY (`id`),
  KEY `idx_platform` (`platform`),
  KEY `idx_report_date` (`report_date`),
  KEY `idx_upload_date` (`upload_date`),
  KEY `idx_plan_name` (`plan_name`),
  KEY `idx_plan_id` (`plan_id`),
  KEY `idx_subject_name` (`subject_name`),
  KEY `idx_subject_id` (`subject_id`),
  KEY `idx_filename` (`filename`),
  KEY `idx_uploaded_by` (`uploaded_by`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `subject_report_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `user` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=166 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='主体报表数据';

-- ecommerce_db.`user` definition

CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(80) NOT NULL,
  `email` varchar(120) NOT NULL,
  `password_hash` varchar(200) NOT NULL,
  `role` varchar(20) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;